name: Build workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lk-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup Python 2
      uses: actions/setup-python@v4
      with:
        python-version: '2.7'

    - name: Build the bootloader
      run: |
        export PYTHON=$(which python2)
        make X5

    - name: Upload bootloader
      uses: actions/upload-artifact@v4
      with:
        name: X5_lk-signed.img
        path: /home/runner/work/lk/lk/build-X5/lk-sign.img
